apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: cmak-docker
build:
  artifacts:
    - image: ghcr.io/eshepelyuk/dckr/cmak2zk
      context: ./cmak2zk
      hooks:
        after:
          - command: ["sh", "-c", "just _latest"]
    - image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5
      context: ./cmak
      hooks:
        after:
          - command: ["sh", "-c", "just _latest"]
      docker:
        buildArgs:
          CMAK_VERSION: "3.0.0.5"
    - image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.6
      context: ./cmak
      hooks:
        after:
          - command: ["sh", "-c", "just _latest"]
      docker:
        buildArgs:
          CMAK_VERSION: "3.0.0.6"
  local:
    push: true
    useBuildkit: true
